#!/bin/bash
ALXroot@60a7d33d9992:/alx-zero_day/0x03-git/bash# cat alx
#!/bin/bash
ALXroot@60a7d33d9992:/alx-zero_day/0x03-git/bash# cat > school
#!/bin/bash
schoolroot@60a7d33d9992:/alx-zero_day/0x03-git/bash# ls
